"use client";

import { useState } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Plus } from "lucide-react";
import { AddVariantDialog } from "./add-verient-dialog";
import DashboardDetails from "./dashboard-details";
import { useTranslations } from "next-intl";


export default function CategoriesContent() {
  const t = useTranslations("ServiceProvider.Categories-Dashboard");
  const stats = [
    {
      label: t("Total Revenue"),
      value: "$45,904",
      change: "+8%",
      note:t("week"),
      changeType:"positive"
    },
    {
      label: t("Overall Rating"),
      value: "4.3",
      change: `45 ${t('reviews')}`,
      changeType: "neutral",
    },
    {
      label: t("Money generated by the provider"),
      value: "$145,674",
      change: "+12%",
      note:t('week'),
      changeType:"positive"
    },
    {
      label: t("Commission earned by Hanat"),
      value: "$1200",
      change: "+12%",
      note:t("week"),
      changeType:"negative"
    },
  ];
  const [isAddVariantOpen, setIsAddVariantOpen] = useState(false);
  const [variants, setVariants] = useState([
    {
      type: "multiple-choice",
      options: ["Kitchen", "Office Space", "Bathroom"],
    },
  ]);

  const [activeTab, setActiveTab] = useState("edit-category");
  const handleAddVariant = (newVariant) => {
    setVariants([newVariant]);
    setIsAddVariantOpen(false);
  };
  return (
    <div className="2xl:p-7 px-7">
      {/* Tab Navigation */}
      <div className="border-b border-gray-200 mb-6">
        <div className="flex">
          <button
            onClick={() => setActiveTab("edit-category")}
            className={`px-4 py-2 2xl:text-sm text-xs font-medium relative ${
              activeTab === "edit-category"
                ? "text-black bg-gray-100"
                : "text-gray-500 hover:text-gray-700"
            }`}
          >
            {t('Edit Category')}
            {activeTab === "edit-category" && (
              <div className="absolute bottom-0 left-0 right-0 h-[1px] bg-black" />
            )}
          </button>
          <button
            onClick={() => setActiveTab("sub-category")}
            className={`px-4 py-2 2xl:text-sm text-xs font-medium relative ${
              activeTab === "sub-category"
                ? "text-black bg-gray-100"
                : "text-gray-500 hover:text-gray-700"
            }`}
          >
            {t('Sub-Category')}
            {activeTab === "sub-category" && (
              <div className="absolute bottom-0 left-0 right-0 h-[1px] bg-black" />
            )}
          </button>
        </div>
      </div>

      {activeTab === "edit-category" ? (
        <div className="space-y-6 w-[50%]">
          <div>
            <label className="block 2xl:text-sm text-xs font-medium text-gray-700 mb-1">
              {t('Category Name')}
            </label>
            <Input
              placeholder={t("Enter Category name")}
              className="border-gray-300"
            />
          </div>
          <div>
            <label className="block 2xl:text-sm text-xs font-medium text-gray-700 mb-1">
              {t('Description')}
            </label>
            <Textarea
              placeholder={t("Enter Description")}
              className="min-h-[200px] border-gray-300"
            />
          </div>
          <div className="flex justify-end space-x-3 pt-4 gap-2">
            <Button variant="outline">{t('Cancel')}</Button>
            <Button className="bg-gray-900 text-white">{t('Save Changes')}</Button>
          </div>
        </div>
      ) : (
        <div>
          {/* Stats Section for Sub-Category */}
          <DashboardDetails stats={stats} />
          <div>
            <h2 className="2xl:text-lg text-sm font-medium mb-4">{t('Sub-category list')}</h2>
            <div className="space-y-6 w-[50%] p-3">
              <div >
                <label className="block 2xl:text-sm text-xs font-medium text-gray-700 mb-1">
                  {t('Sub-Category Name')}
                </label>
                <Input defaultValue="Kitchen"  className="border-gray-300" />
              </div>
              <div>
                <label className="block 2xl:text-sm text-xs font-medium text-gray-700 mb-1">
                  {t('Description')}
                </label>
                <Textarea
                  // placeholder={t("Enter Description")}
                  className="min-h-[120px] border-gray-300"
                />
              </div>
              <div>
                <label className="block 2xl:text-sm text-xs font-medium text-gray-700 mb-2">
                  {t('Add Sub Sub-Category')}
                </label>
                <div className="flex flex-wrap gap-2 mb-3">
                  {variants.map((variant, vIndex) =>
                    variant.options.map((option, index) => (
                      <span
                        key={`${vIndex}-${index}`}
                        className="bg-blue-50 text-blue-700 px-3 py-1 rounded-full 2xl:text-sm text-xs"
                      >
                        {option}
                      </span>
                    ))
                  )}

                  <Button
                    variant="outline"
                    size="sm"
                    className="border-gray-300 text-gray-700 rounded-full px-3 py-1 h-auto 2xl:text-sm text-xs"
                    onClick={() => setIsAddVariantOpen(true)}
                  >
                                <Plus className="h-4 w-4 2xl:mr-2 mr-1" />
                     {t('Add new')}
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
      <AddVariantDialog
        open={isAddVariantOpen}
        onOpenChange={setIsAddVariantOpen}
        initialVariants={variants}
        onSave={handleAddVariant}
      />
    </div>
  );
}
