"use client"
import DashboardDetails from "./dashboard-details"
import { DataTable } from "./data-table"
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar"
import { Badge } from "./ui/badge"
import { AlertTriangle, ArrowLeft, CircleAlert, CircleCheck, EllipsisVertical } from "lucide-react"
import BookingIcon from "@/public/images/Booking_management-Icon.png"
import Image from "next/image"
import Link from "next/link"
const ServiceProviderBooking = () => {
      const columns = [
    {
      header: "Booking ID",
      accessorKey: "id",
    },
    {
      header: "Type",
      accessorKey: "type",
    },
    {
      header: "Customer name",
      accessorKey: "customer",
       cell: (row) => (
        <div className="flex items-center gap-3">
          <Avatar className="h-8 w-8">
            <AvatarImage src={row.customer.avatar || "/placeholder.svg"} alt={row.customer.name} />
            <AvatarFallback>{row.customer.name}</AvatarFallback>
          </Avatar>
          <span className="font-medium">{row.customer.name}</span>
        </div>
      ),
    },
    {
      header: "Service",
      accessorKey: "service",
    },
    {
      header: "Resource",
      accessorKey: "resource",
       cell: (row) => (
        <div className="flex items-center gap-3">
          <Avatar className="h-8 w-8">
            <AvatarImage src={row.resource.avatar || "/placeholder.svg"} alt={row.resource.name} />
            <AvatarFallback>{row.resource.name}</AvatarFallback>
          </Avatar>
          <span className="font-medium">{row.resource.name}</span>
        </div>
      ),
    },
      {
      header: "Booking Date",
      accessorKey: "date",
    },
    {
      header: "Status",
      accessorKey: "status",
      cell: (row) => (
            <Badge
                variant="outline"
                className="text-muted-foreground rounded-md gap-0.5 px-1.5 text-xs"
              >
                {row.status==="Completed" ? <CircleCheck className="fill-green-500 dark:fill-green-400 w-[13px] h-[13px] text-white" />: row.status==="Cancelled"? <CircleAlert className="fill-red-500 dark:fill-red-400 w-[13px] h-[13px] text-white" /> :  <AlertTriangle className="h-4 w-4 text-white fill-orange-500" /> }
                {row.status}
              </Badge>
      ),
    },
    {
      header: "Action",
      accessorKey: "action",
      cell: (row) => (
        <div className="flex justify-center gap-2">
          <EllipsisVertical className="h-4 w-4" />
        </div>
      ),
    },
  ]

  const stats = [
    {
      label: "Total Bookings",
      value: "1200",
      change: "+12",
      note:"vs last week",
      changeType: "positive",
    },
    {
      label: "Total Revenue",
      value: "$45,904",
      change: "+8%",
      note:"vs last week",
      changeType: "negative",
    },
    {
      label: "Money generated by the provider",
      value: "$145,674",
      change: "+12%",
      note:"vs last week",
      changeType: "negative",
    },
    {
      label: "Commission earned by Hanat",
      value: "$1200",
      change: "+12%",
      note:"vs last week",
      changeType: "positive",
    },
  ]

  const bookings = [
    {
      id: "ONE-Z2A3B4",
      type: "External",
      customer: { name: "Robert Fox", avatar: "/placeholder.svg?height=32&width=32" },
      service: "Personal Chef",
      resource: { name: "Wade Warren", avatar: "/placeholder.svg?height=32&width=32" },
      date: "Feb 2, 2024",
      status: "Pending",
    },
    {
      id: "ONE-Q3R4S5",
      type: "Hanat",
      customer: { name: "Eleanor Pena", avatar: "/placeholder.svg?height=32&width=32" },
      service: "Car Cleaning",
      resource: { name: "Jane Cooper", avatar: "/placeholder.svg?height=32&width=32" },
      date: "Dec 30, 2024",
      status: "Completed",
    },
    {
      id: "ONE-7G8H9I",
      type: "Hanat",
      customer: { name: "Wade Warren", avatar: "/placeholder.svg?height=32&width=32" },
      service: "Home Cleaning",
      resource: { name: "Devon Lane", avatar: "/placeholder.svg?height=32&width=32" },
      date: "Mar 20, 2024",
      status: "Cancelled",
    },
  ]
  return (
       <div className="p-7 space-y-6">
        <div className="flex gap-4">
           {/* <Link href="/admin/dashboard" className="text-muted-foreground">
                <ArrowLeft className="h-8 w-8 border p-2 rounded-full " />
              </Link> */}
                    <Image src={BookingIcon} className="2xl:h-12 h-10 w-10 2xl:w-12 border border-r-2 rounded-full p-2" alt="User Icon" />
                    <div>
                      <h1 className="2xl:text-lg text-sm font-semibold">Booking Management</h1>
                      <p className="text-xs text-muted-foreground">
                        Lorem ipsum management
                      </p>
                    </div>
                  </div>
      <DashboardDetails stats={stats} />
      <DataTable
        data={bookings}
        columns={columns}
        searchField="customer.name"
        monthlyFilter={["Daily","Weekly","Monthly","Yearly"]}
        className="mt-6" />
    </div>
  )
}

export default ServiceProviderBooking